### ISSUE TITLE
App is not available in your region

### ISSUE THREAD

**Issue by EmmanuelMess** [UweTrottmann/SeriesGuide#1008]
**Describe the bug**
Can't download app for my Nokia 2.4m in Argentina.

**To Reproduce**
1. Go to Argentina
2. Open Google Play Store and search "SeriesGuide"
3. Error appears on top of search, "App is not available in your region".
 
**Expected behavior**
App should be available.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 2.4m
 - OS: Android 12

**Additional context**

**Comment by UweTrottmann** [comment]
The app is not available in Argentina because unlike for some other regions I would have to collect VAT myself (instead of Google handling it). Until that changes I can't offer the app there.

Note that you can still get the APK from GitHub. Using any subscription-only features will not be possible though.
