### ISSUE TITLE
Unable to rate some movies

### ISSUE THREAD

**Issue by Technicolour** [UweTrottmann/SeriesGuide#428]
I'm not getting the trakt rate section on some movies such as Whiplash (2014).

**Comment by UweTrottmann** [comment]
You can only rate a movie if you add it to your watchlist or collection. Or is this an issue with this specific movie?

**Comment by Technicolour** [comment]
I didn't think there would be a restriction on which movies I could rate. I just noticed that some the option wasn't there. Looking at it, it does look to be that I can rate movies of they are om y watchlist or collection.

It would be nice to have the app work as trakt does and be able to rate any movie and if you haven't marked it as seen, when you rate it, it is also marked as seen.

**Comment by UweTrottmann** [comment]
Currently don't have a way to get ratings or watched/watchlist/collection status for single movies with trakt v2, so that was the quick fix (as state gets synced only for movies in the SG database, which are those in watchlist/collection).

Will hopefully improve with some trickery (like database caching all movie states).

**Comment by UweTrottmann** [comment]
With https://github.com/UweTrottmann/SeriesGuideInternal/commit/aca338707c922ccbe125c8e7a6b2a53d2f6d3a1e rating of watched movies is now possible as well.
