### ISSUE TITLE
Purple vs. Green Status

### ISSUE THREAD

**Issue by ming13** [UweTrottmann/SeriesGuide#441]
I think various green status appearances can be painted with the primary purple color.

* [New show](https://cloud.githubusercontent.com/assets/200401/6390813/9f11ae32-bdc0-11e4-9c5e-aa8e8de72d9f.png).
* [Show](https://cloud.githubusercontent.com/assets/200401/6390816/9f2c4940-bdc0-11e4-8710-f70d02c8f9c0.png).
* [Show overview](https://cloud.githubusercontent.com/assets/200401/6390815/9f166ff8-bdc0-11e4-96a6-e6ef928f4883.png).
* [Season](https://cloud.githubusercontent.com/assets/200401/6390814/9f140588-bdc0-11e4-90e9-abb27d350e5e.png)

The green color seems out of place actually, because all colors are either purple or white or grey.

My original intent was to make a pull request, because it seems like a not finished theming for me, but naming of `R.attr.textColorSgGreen` and `R.style.TextAppearance_Subhead_Dim` made me think it is intentional.

**Comment by UweTrottmann** [comment]
It is intentional (the teal text is meant to maintain visual compatibility with older versions, where the color was green).

Anyhow, the latest beta has experimentally changed the accent color from purple to teal ("green") to increase consistency. [Check it out.](https://github.com/UweTrottmann/SeriesGuide/wiki/Beta)

**Comment by ming13** [comment]
Well, it seems like I started to use SG after purple invasion :smile: Anyway, for me personally SG is purple, its mix with teal seems not so great. Your call! :purple_heart: :space_invader: :grapes:
