### ISSUE TITLE
Add Support for Android M

### ISSUE THREAD

**Issue by Nemisis** [UweTrottmann/SeriesGuide#470]
With the final SDK, it is now a good opportunity to update the build tools and push the target SDK version to 23 as well as account for the storage permission that the app uses.

**Comment by JakeWharton** [comment]
The build tools and compile SDK version should be updated to 23 first. That's just updating a number. Then I would recommend doing the target SDK update as a separate follow-up as it's behavior change.

**Comment by UweTrottmann** [comment]
Sorry for the delay, I'm on this currently!

Would have done this right after Google IO (in May, *gasp*), but immediately afterwards started a new job, then had to setup a new apartment. Then quit that job for one with less time commitment to do more SeriesGuide again. Then since last week's beta my family and me did help some Ukrainian refugees set up their apartment my parents are providing them... :)

@JakeWharton Yeap, that's what I've thought ;) But I was surprised to see that the not too old Google Play Services and Google API client releases SG uses still use Apache HTTP, breaking the build -.- Well, library update time (because I don't want to set `useLibrary 'org.apache.http.legacy'`).

**Comment by eleonrk** [comment]
As a ukrainian and a big fan of your work, thank you very much !!

**Comment by UweTrottmann** [comment]
@eleonrk Thanks! And oh, this issue is closed already since `25-beta2`.
