### ISSUE TITLE
Show info not updated if "GetAccounts" is blocked

### ISSUE THREAD

**Issue by frikisama** [UweTrottmann/SeriesGuide#475]
I don't know if this is an intended behavior, and if it is feel free to close this, but please read below first.

Since some version in September it is not possible to refresh any show's information if the permission "GetAccounts" and/or "GetAccountsByType" is blocked, in my case by XPrivacy. I see this as a regression, since the ability to get this information isn't (or shouldn't be) related to any account at all, as it is freely available, and it was working perfectly fine before. My best guess is it has something to do with the commits on or around September 10th, but I haven't looked too deep in the code to see where this is coupled with the ability to update the shows.

If this is an intended behavior I kindly ask you to reconsider, since this is just an artificial dependency (it was working before) and there are people who value privacy and don't see the necessity of sharing information about what accounts they use with a show tracking app, or the necessity at all to couple updating shows information to a private account, specially if they don't use any of the features for which an account is actually best used for (cloud sync, etc.).

Thanks!

**Comment by UweTrottmann** [comment]
This permission has been required since a few years now. See
http://seriesgui.de/privacy.

This might be related to the update to provide compatibility with the new
permission model in Android 6.0? Possibly XPrivacy does not support apps
targeted at API level 23?

SeriesGuide uses an account to tie into the Android syncing framework. To
get its existing one the accounts permissions are required on Android
versions below 6.0.
Am 07.10.2015 11:23 schrieb "frikisama" <notifications@github.com>:

**Comment by frikisama** [comment]
I know this permission has been required for some time, and it isn't actually needed for show information updates since this has worked without a hitch until now while having any access to accounts blocked. I don't know if XPrivacy supports API level 23, but the underlying problem I'm trying to explain is that an account, and/or any account information, is needed AT ALL even to manually update the shows. Before it was possible to just block these permissions if the cloud sync wasn't needed and you just wanted a simple show tracking system with offline backup and up-to-date information, but right now it is not possible anymore.

Please consider decoupling at least manual show information update from accounts and synchronization features!

**Comment by UweTrottmann** [comment]
The only changes to the sync code since 2014 is the usage of a new account
removal method on Lollipop and up (see
https://github.com/UweTrottmann/SeriesGuide/tree/master/SeriesGuide/src/main/java/com/battlelancer/seriesguide/sync
).

SG definitely requires an account to use a sync adapter to update shows for
a long time. It allows Android to decide when the best time for syncing
data is. It may be possible that XPrivacy has still allowed SG access to
its own account without the permission (which is now also the default
behavior in Android 6.0).

By chance, did the SeriesGuide account get removed? You may try adding it
again manually in Android Settings > Accounts if you won't give permission
to the app.
Am 07.10.2015 12:51 schrieb "frikisama" <notifications@github.com>:

**Comment by frikisama** [comment]
Hhmmm, I don't think XPrivacy allows access to the own account when account access is blocked, so this 6.0 feature is actually even cooler than I thought!

No, the account wasn't removed, and I tried allowing all combinations of the permissions XPrivacy controls, but since last month it definitely needs GetAccounts, and GetAccountsByType with com.battlelancer.seriesguide as parameter, to update show information. It's nice to autosync with android's built in account sync, but is it possible to make manual sync not rely on the account? Is the sync logic tied to the account sync, or does the account sync just call a sync method? Sorry if it's a stupid question: like I said, I didn't get much into SG's code, so I don't know how deep accounts and information update are linked!

Anyway, eagerly awaiting Marshmallow with the much needed privacy updates!

Dankeschön!
