### ISSUE TITLE
Tv showes images are blank 

### ISSUE THREAD

**Issue by docsuleman** [UweTrottmann/SeriesGuide#530]
I compiled app using Android studio. Everything works fine after putting my own api but tv showes images are not getting displayed. I followed the clear cache instructions but still blank. 
![screenshot_20171227-010041](https://user-images.githubusercontent.com/10552811/34363892-f1709376-eaa1-11e7-91e0-1f9d95453359.png)

**Comment by UweTrottmann** [comment]
This is because since a few releases SeriesGuide uses an image cache server, which is not publicly available.

However, I made some changes so the app will no fall back to using the TheTVDB servers directly if no image cache server is defined. Pull from the dev branch, then build again.

Thanks for reporting!

**Comment by docsuleman** [comment]
Thanks. I removed the cache code altogether to get some away around. its was poor straregy but i needed something.
